### ISSUE TITLE
qo on PyPI

### ISSUE THREAD

**Issue by ryanhiebert** [otosense/ooq#1]
Hi @thorwhalen and @SRHerzog, the watchers of this repository. I'm reaching out to see if you might be willing to let me have the `qo` name on PyPI.

It looks like there are 3 names on PyPI that are hosting what seems to essentially be the package at this repository, `ooq`, `oq` and `qo`. I'd really like to use the name `qo`, and I would really appreciate if you would consider allowing me to own that name on PyPI.

I want to use it for a task management library I've been working on. Think Celery, but about goodies on top of Celery rather than the low-level details. A more capable version of celery signatures.

Here's some of the code that would be released using that name if you gave me ownership of the name. https://github.com/aspiredu/qo

A bit about me is that I created `tox-travis`, I maintain `aldjemy` and the Python `hirefire` package, as well as `django-safemigrate` and several others.

Would you be willing to consider letting me have the name `qo` on PyPI?

**Comment by thorwhalen** [comment]
Hi Ryan,

Would you be willing to take oq or ooq instead?

The story is; it was meant to be `qo` originally (for "Quick (access to)
Other's favorite imports", also appropriate because "qo <-> co(de)").
When I tried to package it I got errors (which I assumed were "fatal" --
even though I didn't see any package of that name).
So I changed it to ot, then oq, the ooq which finally went through.

What I didn't know is that I had created 3 packages on the way.
I haven't worked on it since, and can let the idea settle a bit, since
perhaps it's more important to you than me -- but if you can settle
of oq or ooq, I can liberate that now.

Thor.

**Comment by ryanhiebert** [comment]
I really appreciate the response, thank you! `qo` is really the one I want, if I can convince you to allow me to use it.

There are two primary primitives that I'm planning for this, `qo.routine`, and `qo.operation`. I really like the play on sounds that `qo` can be pronounced `co`, making those pronounced "coroutine" and "cooperation". It's "cute", but I'm rather fond of it.

**Comment by thorwhalen** [comment]
I understand -- that's what I liked about it too.
qo-de (code)
Let's leave that settled, and I'll see if I can loosen the grip of
attachment or find something else to be attached to.

For sure, your tool has a further reach than what I intended mine for.

**Comment by ryanhiebert** [comment]
I really appreciate you being willing to give it consideration.

**Comment by ryanhiebert** [comment]
At the risk of putting down your work here, I'm trying to come up with a better name for what you're doing to see if I can come up with another name you might be happy with, but instead I'm having a really hard time understanding the value you're trying to add with this library.

For example, if I was trying to share my own personal medley, I might think to create a package called `rdh-utils` (RDH is my initials) or something similar. I wouldn't think to add my personal medley to a package like this, because I wouldn't expect that I would have the autonomy I'd want to upload and change my functions the way I'd desire. Additionally, it seems odd that I'd install several other people's medleys into my environment in order to access my own functions, or the functions of some particular person whose style I'd like to follow. I imagine I'd rather install a package that had their medley directly.

Do you understand my confusion, and can you help me understand your motivations a bit more? If I can understand what you're doing a bit better, perhaps I might have some more success finding a resolution to our competing interests in the name `qo`.

**Comment by thorwhalen** [comment]
That's because what you see there isn't the end -- I just interrupted my
initial intent.

The intent was to have *q*uick access to my own *qo*de favorites as well as
my *qo*leagues (and eventually, perhaps from a wider net of *qo*
ntributors).

Right now, it's just a POC with one contributor (me), and several users
(myself and a few others), but I intend to do more, as I have time.

It's not meant to be used in a production environment obviously, but
amongst us data scientists that use notebooks heavily, and are constantly
bringing together pieces from here and there.

I was fed up:
(1) Losing time in those "wait... was from scipy.spatial... or..."
(2) Having to ask colleagues where they imported something from (because in
notebooks, your environment can import stuff behind the scenes (not ideal
for sharing))

So you see, in and of itself, qo is useful to me (and some others) now.
The package you're developing doesn't, for me, and might never -- though
surely has more use for the wider community, at least a priori.

**Comment by ryanhiebert** [comment]
Gotcha, thanks. If it were me, I'd probably want to just release a separate package rather than include my stuff in a super package like this. Anyway, thanks for expanding on what you're wanting to do.

I'll let you think on it for a bit, then. I appreciate you considering allowing me to use the name.

**Comment by ryanhiebert** [comment]
Hi! How has the idea of letting me have the `qo` name settled in your mind? We're beginning to use this more in production, so I expect that I'll be ready to release it in the next couple of months.

**Comment by thorwhalen** [comment]
Responded directly via email.
